# Generated by Django 3.2 on 2021-04-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KNTLword',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.TextField(unique=True)),
                ('word_desc', models.TextField()),
            ],
            options={
                'db_table': 'KNTLword',
                'managed': False,
            },
        ),
    ]
