BEGIN TRANSACTION;
CREATE TABLE KNTLword ( word_id INTEGER PRIMARY KEY, word TEXT NOT NULL UNIQUE, word_desc TEXT NOT NULL);
INSERT INTO "KNTLword" VALUES(1,'AMATOL','Bahan peledak campuran antara trinitrotoluena dan amonium nitrat');
INSERT INTO "KNTLword" VALUES(2,'BANJOL','Kain yg bergambar-gambar indah, bercorak biru atau kuning pd dasar merah');
INSERT INTO "KNTLword" VALUES(3,'BANTAL','Alas kepala, alas duduk, sandaran punggung, dsb yg dijahit spt karung, diisi dng kapuk, sabut, dsb;');
INSERT INTO "KNTLword" VALUES(4,'BANYOL','Lucu; jenaka;');
INSERT INTO "KNTLword" VALUES(5,'BENCOL','Berbenjol-benjol');
INSERT INTO "KNTLword" VALUES(6,'BENDOL','Memberi asap kpd, Memasak (mengeringkan, membersihkan, mengharumkan, dsb) dng asap;');
INSERT INTO "KNTLword" VALUES(7,'BENJOL','Bengkak atau bincul (pd dahi atau kepala);');
INSERT INTO "KNTLword" VALUES(8,'BENSOL','Bensol --> benzol');
INSERT INTO "KNTLword" VALUES(9,'BENTIL','Bentil --> pentil');
INSERT INTO "KNTLword" VALUES(10,'BENTOH','Bantah');
INSERT INTO "KNTLword" VALUES(11,'BENTOK','Kebentok');
INSERT INTO "KNTLword" VALUES(12,'BENTOL','Bintik-bintik (agak besar) yg timbul pd tubuh;');
INSERT INTO "KNTLword" VALUES(13,'BENTOS','Organisme yg mendiami daerah dasar perairan');
INSERT INTO "KNTLword" VALUES(14,'BENTUL','Tumbuhan berumbi, daun muda dan tangkai mudanya dapat disayur, umbinya dapat dimakan; talas; colocasia esculenta');
INSERT INTO "KNTLword" VALUES(15,'BENZOL','Campuran benzena dng hidrokarbon aromatik yg diperoleh dr gas batu bara atau ter batu bara');
INSERT INTO "KNTLword" VALUES(16,'BINTAL','Bintil (agak besar)');
INSERT INTO "KNTLword" VALUES(17,'BINTIL','Bintul (bercak) kecil (spt bekas digigit nyamuk);');
INSERT INTO "KNTLword" VALUES(18,'BINTUL','Bengkak kecil pd kulit (krn digigit nyamuk, disengat lebah, dsb)');
INSERT INTO "KNTLword" VALUES(19,'BONBON','Gula-gula; permen; kembang gula');
INSERT INTO "KNTLword" VALUES(20,'BONCEL','Kecil');
INSERT INTO "KNTLword" VALUES(21,'BONCOL','Jendul');
INSERT INTO "KNTLword" VALUES(22,'BONDOL','Burung kecil berkepala putih; pipit uban; emprit kaji; munia maja');
INSERT INTO "KNTLword" VALUES(23,'BONDOT','Berkas; ikatan (padi dsb);');
INSERT INTO "KNTLword" VALUES(24,'BONGOK','Besar (gemuk) tetapi pendek; tidak seimbang (besar dng tingginya)');
INSERT INTO "KNTLword" VALUES(25,'BONGOL','Bersangkutan dng perbuatan (verba) yg dilakukan untuk orang lain, msl verba dl kalimat ibu membukakan ayah pintu');
INSERT INTO "KNTLword" VALUES(26,'BONJOL','Bonjol --> bonggol, Bonjol --> boncol');
INSERT INTO "KNTLword" VALUES(27,'BONJOR','Kubu');
INSERT INTO "KNTLword" VALUES(28,'BONTAK','Gemuk bulat (tt pipi dsb)');
INSERT INTO "KNTLword" VALUES(29,'BONTOK','Bonto');
INSERT INTO "KNTLword" VALUES(30,'BONTOT','Bungsu');
INSERT INTO "KNTLword" VALUES(31,'BONYOK','Memar dan lunak (tt buah dsb); sangat lembek dan agak busuk (tt makanan, ikan, dsb)');
INSERT INTO "KNTLword" VALUES(32,'BONYOR','Bonyor --> bonyok');
INSERT INTO "KNTLword" VALUES(33,'BORGOL','Belenggu tangan terbuat dr besi, berbentuk bulat, dapat ditutup dan dibuka dng memakai kunci;');
INSERT INTO "KNTLword" VALUES(34,'BORKOL','Borkol --> brokoli');
INSERT INTO "KNTLword" VALUES(35,'BORTEL','Wortel');
INSERT INTO "KNTLword" VALUES(36,'BUNTAL','Gembung; buncit, Ikan laut berbisa yg dapat menggembungkan perutnya bila tersentuh, bermacam-macam jenisnya');
INSERT INTO "KNTLword" VALUES(37,'BUNTEL','Bungkusan; bungkus kecil');
INSERT INTO "KNTLword" VALUES(38,'BUNTIL','Lauk yg dibuat dr parutan kelapa muda (biasanya dicampuri ikan teri, diberi bumbu bawang, cabai, lengkuas, asam, garam, dsb), dibungkus dng daun keladi, pepaya, atau daun singkong dan dikukus, Pundi-pundi yg dasarnya berpapan (untuk membawa pakaian dsb);');
INSERT INTO "KNTLword" VALUES(39,'CANTEL','Sorgum, Mencantelkan');
INSERT INTO "KNTLword" VALUES(40,'CANTOL','Mencantolkan (men.can.tol.kan), mengaitkan pd; menggantung pd; menyangkut pd;');
INSERT INTO "KNTLword" VALUES(41,'CENDOL','Penganan yg dibuat dr tepung beras dsb yg dibentuk dng penyaring, kemudian dicampur dng air gula dan santan (untuk minuman)');
INSERT INTO "KNTLword" VALUES(42,'CENTIL','Suka bergaya (tt gadis); genit;');
INSERT INTO "KNTLword" VALUES(43,'CONGOK','Mencongok (men.co.ngok), berdiri (atau duduk) tegak-tegak; conggok');
INSERT INTO "KNTLword" VALUES(44,'CONGOL','Mencongol (men.co.ngol), menyembul (menonjol) ke luar; menganjur ke atas');
INSERT INTO "KNTLword" VALUES(45,'CONGOR','Jungur');
INSERT INTO "KNTLword" VALUES(46,'CONTEK','Sontek');
INSERT INTO "KNTLword" VALUES(47,'CONTOH','Barang atau sebagian dr barang yg rupa, macam, dan keadaannya sama dng semua barang yg ada; barang yg dapat mewakili barang yg lain krn sama sifat-sifatnya, Sesuatu yg akan atau yg disediakan untuk ditiru atau diikuti, Pola (untuk membatik, membuat pakaian, dsb), Model (rumah, pesawat terbang, dsb dl bentuk kecil untuk memperlihatkan bagaimana rupa rumah, pesawat terbang, dsb sesungguhnya atau yg akan dibuat), Teladan (tt kelakuan, perbuatan, dsb); hal (spt peristiwa) yg menjadi teladan');
INSERT INTO "KNTLword" VALUES(48,'DENTAL','A berhubungan dng gigi atas dl proses artikulasi suatu bunyi;, A terjadi krn penyempitan atau persentuhan antara (ujung) lidah dan gigi;, N bunyi terbentuk dng cara demikian');
INSERT INTO "KNTLword" VALUES(49,'DOKTOR','Gelar kesarjanaan tertinggi yg diberikan oleh perguruan tinggi kpd seorang sarjana yg telah menulis dan mempertahankan disertasinya;');
INSERT INTO "KNTLword" VALUES(50,'DOMPOL','Berdompol (ber.dom.pol), bergerombol (tt buah-buahan spt buah duku, rambutan, dan anggur);');
INSERT INTO "KNTLword" VALUES(51,'DONDON','Warna atau corak (kain dsb);, Mendondon (men.don.don), menggadai(kan) sawah; menyerahkan hasil tanah dng sejumlah uang sbg penukarnya');
INSERT INTO "KNTLword" VALUES(52,'DONGOK','Pendek gemuk; tidak ramping (bentuk badan yg tidak seimbang), Dungu; tolol');
INSERT INTO "KNTLword" VALUES(53,'FANTOM','Bentuk khayal tt sesuatu (terutama tt bentuk manusia)');
INSERT INTO "KNTLword" VALUES(54,'FOETAL','Retribusi yg harus dibayar krn mengambil hasil tanah milik orang lain (di halmahera)');
INSERT INTO "KNTLword" VALUES(55,'GANTAL','Gulungan daun sirih yg dipakai untuk sesaji dsb');
INSERT INTO "KNTLword" VALUES(56,'GANTEL','Menggantelkan');
INSERT INTO "KNTLword" VALUES(57,'GANTOL','Kait;');
INSERT INTO "KNTLword" VALUES(58,'GENTEL','Butir (bulatan spt pil); gelintir;');
INSERT INTO "KNTLword" VALUES(59,'GONDOK','Gemuk pendek (tt badan, leher, barang);, N penyakit bengkak pd leher depan krn kelenjar yg menjadi besar; beguk, Mendongkol; marah yg tertahan');
INSERT INTO "KNTLword" VALUES(60,'GONDOL','Menggondol (meng.gon.dol), menggonggong (membawa dng mulut), Menggondol (meng.gon.dol), ki membawa lari; mencuri, Menggondol (meng.gon.dol), ki mendapat piala tanda kemenangan (hadiah dsb) dl pertandingan dsb; menerima atau mengantongi (ijazah dsb)');
INSERT INTO "KNTLword" VALUES(61,'GONGOK','Perkakas rumah tangga dsb yg cekung dan bertangkai sbg alat untuk menyauk air, nasi, pasir, dsb;');
INSERT INTO "KNTLword" VALUES(62,'GONIOM','Bahan pewarna makanan buatan yg tidak berbahaya, dibuat dr fermentasi beras dng zat monascus purpureus');
INSERT INTO "KNTLword" VALUES(63,'GONJOK','Menggonjokkan (meng.gon.jok.kan), memperolokkan');
INSERT INTO "KNTLword" VALUES(64,'GONTAI','Lambat (dr yg lain); perlahan-lahan dan agak terhuyung-huyung (krn lemah dsb); lembam');
INSERT INTO "KNTLword" VALUES(65,'GONTOK','Bergontok (ber.gon.tok), berkelahi; tinju-meninju;, Bergontok (ber.gon.tok), ki berselisih; bertengkar');
INSERT INTO "KNTLword" VALUES(66,'GONYEL','Menekan-nekan atau memijit-mijit perlahan-lahan (pd orang sakit);, Menggonyeh; menggigit-gigit puting susu (tt bayi)');
INSERT INTO "KNTLword" VALUES(67,'GONYOH','Menggonyoh (meng.go.nyoh), menggosok (membersihkan)');
INSERT INTO "KNTLword" VALUES(68,'GONYOK','Mendendam mengenai suatu hal');
INSERT INTO "KNTLword" VALUES(69,'GUNTIL','N pundi-pundi kecil');
INSERT INTO "KNTLword" VALUES(70,'HONCOE','Pipa lengkung untuk mengisap tembakau yg salah satu ujungnya berbentuk cawan sbg tempat tembakau yg akan disulut');
INSERT INTO "KNTLword" VALUES(71,'HOSTEL','Tempat untuk menginap yg murah (biasanya mendapat bantuan pemerintah) bagi mahasiswa, karyawan yg sedang dl pelatihan dsb; asrama');
INSERT INTO "KNTLword" VALUES(72,'JENDOL','Jendul');
INSERT INTO "KNTLword" VALUES(73,'JONGOS','Pembantu rumah tangga (laki-laki); pelayan; bujang');
INSERT INTO "KNTLword" VALUES(74,'JONJOT','Menjonjot (men.jon.jot), mencabut (menjemput) hanya dng sekali cabut atau jemput saja (thd tembakau, kapas, dsb);');
INSERT INTO "KNTLword" VALUES(75,'JONTOH','Dongeng yg bertalian dng adat');
INSERT INTO "KNTLword" VALUES(76,'JONTOR','Bengkak (pd bibir) akibat kena pukul, disengat lebah, dsb');
INSERT INTO "KNTLword" VALUES(77,'KANCIL','Binatang pemakan tanaman yg cepat larinya, berbadan langsing, kaki depan lebih pendek dp kaki belakang, bulunya berwarna cokelat kemerah-merahan, jenis jantan bertaring, mencuat ke luar dari atas rahang; tragulus javanicus;, Ki tokoh utama binatang yg cerdik dl cerita rakyat di asia tenggara;, Ki orang yg cerdik dan licik (banyak akal)');
INSERT INTO "KNTLword" VALUES(78,'KANDEL','Tebal;, Ki banyak uang');
INSERT INTO "KNTLword" VALUES(79,'KANDIL','Pelita; lampu; (tempat) lilin');
INSERT INTO "KNTLword" VALUES(80,'KANDUL','Bakul (keranjang) yg biasa digunakan ketika membuat gambir, Lipatan pd ujung jala yg membentuk kantong;');
INSERT INTO "KNTLword" VALUES(81,'KANJAL','Terhenti krn terhalang dsb');
INSERT INTO "KNTLword" VALUES(82,'KANSEL','Mengansel (me.ngan.sel), membatalkan');
INSERT INTO "KNTLword" VALUES(83,'KANTAN','Halia hutan yg bunganya dapat dirujak atau digunakan sbg bumbu gulai; nicolaia imperalis');
INSERT INTO "KNTLword" VALUES(84,'KANTAR','Berkantaran (ber.kan.tar.an), berkobar-kobar');
INSERT INTO "KNTLword" VALUES(85,'KANTER','Alat untuk mengukur zat cair');
INSERT INTO "KNTLword" VALUES(86,'KANTIH','Benang tenun');
INSERT INTO "KNTLword" VALUES(87,'KANTIL','Bunga cempaka putih, michelia alba');
INSERT INTO "KNTLword" VALUES(88,'KANTIN','Ruang tempat menjual minuman dan makanan (di sekolah, di kantor, di asrama, dsb)');
INSERT INTO "KNTLword" VALUES(89,'KANTOR','Balai (gedung, rumah, ruang) tempat mengurus suatu pekerjaan (perusahaan dsb);, Tempat bekerja;');
INSERT INTO "KNTLword" VALUES(90,'KANTUK','Rasa hendak tidur');
INSERT INTO "KNTLword" VALUES(91,'KANWIL','Orang (perempuan) yg mampu membaca dan menulis');
INSERT INTO "KNTLword" VALUES(92,'KANYON','Lembah yg sempit dan dalam dng tepi yg terjal, biasanya ada sungai yg mengalir di dasarnya; jurang');
INSERT INTO "KNTLword" VALUES(93,'KARBOL','Benda cair berwarna putih dan berbusa spt air sabun serta berbau harum yg dapat dipakai untuk mematikan kuman penyakit; c6h5oh;');
INSERT INTO "KNTLword" VALUES(94,'KARTAL','Radang jaringan tubuh yg memungkinkan timbulnya rongga tempat nanah mengumpul');
INSERT INTO "KNTLword" VALUES(95,'KARTEL','Organisasi perusahaan besar (negara dsb) yg memproduksi barang yg sejenis;, Man persetujuan sekelompok perusahaan dng maksud mengendalikan harga komoditas tertentu, Kerja sama yang saling menguntungkan antara beberapa pengusaha atau perusahaan, seperti dalam penentuan harga, jumlah dan daerah pemasaran untuk membatasi persaingan antara mereka sehingga memperoleh semacam kedudukan yang bersifat monopoli (cartel), Perjanjian yang dilarang, antara pelaku usaha dengan pelaku usaha pesaingnya, yang bermaksud untuk mempengaruhi harga dengan mengatur produksi dan atau pemasaran suatu barang dan atau jasa, yang dapat mengakibatkan terjadinya praktek monopoli dan atau persaingan usaha tidak sehat.');
INSERT INTO "KNTLword" VALUES(96,'KARTON','Kertas tebal (untuk kulit buku, gambar, dsb) dng berat dasar antara 150—600 g;');
INSERT INTO "KNTLword" VALUES(97,'KARTOT','Sangat tidak suka');
INSERT INTO "KNTLword" VALUES(98,'KASTAL','Pohon kayu yg tumbuh di gurun atau di tanah yg kering');
INSERT INTO "KNTLword" VALUES(99,'KASTEL','Rumah (benteng) yg dikelilingi parit;, Istana yg sekaligus dijadikan benteng');
INSERT INTO "KNTLword" VALUES(100,'KASTIL','Kastil --> kastel');
INSERT INTO "KNTLword" VALUES(101,'KASTOR','Membarut atau mengikat (dng perban, kain, dsb)');
INSERT INTO "KNTLword" VALUES(102,'KATROL','Alat pengangkat dr besi; kerek');
INSERT INTO "KNTLword" VALUES(103,'KEMBOL','Mengembol (me.ngem.bol), menjadi besar krn penuh (tt kantong baju dsb)');
INSERT INTO "KNTLword" VALUES(104,'KENDAL','Pohon yg buahnya lebat berwarna merah muda dan licin, spt buah kersen, cabang-cabangnya membengkok ke bawah; cordia obliqua;, Buah kendal');
INSERT INTO "KNTLword" VALUES(105,'KENDIL','Periuk');
INSERT INTO "KNTLword" VALUES(106,'KENDOR','Kendor --> kendur');
INSERT INTO "KNTLword" VALUES(107,'KENSEL','Meniadakan; menghapuskan; membatalkan;, Menunda');
INSERT INTO "KNTLword" VALUES(108,'KENTAL','Antara cair dan keras; pekat (tidak cair); hampir beku, Akrab (tt persahabatan); karib, Cak memperlihatkan keasliannya (tt pengucapan bahasa)');
INSERT INTO "KNTLword" VALUES(109,'KENTAR','Ukuran berat untuk menimbang emas');
INSERT INTO "KNTLword" VALUES(110,'KENTUM','Misal; umpama; perumpamaan');
INSERT INTO "KNTLword" VALUES(111,'KENTUT','Gas berbau busuk (gas busuk) yg keluar dr anus;, Kentutan (ken.tut.an), tumbuhan yg daunnya berbau tidak sedap, biasa digunakan untuk obat sakit perut dsb; paederia foetida;, Kentutan (ken.tut.an), daun kentutan');
INSERT INTO "KNTLword" VALUES(112,'KENYAL','Empuk dan berdaya pantul (apabila ditekan kembali ke bentuk semula, spt bola karet);, Liat (tt daging dsb);');
INSERT INTO "KNTLword" VALUES(113,'KINTAL','Katak yg dapat menggembungkan perutnya');
INSERT INTO "KNTLword" VALUES(114,'KINTAR','Kintar --> kitar');
INSERT INTO "KNTLword" VALUES(115,'KINTIL','Ikut dl perjalanan;');
INSERT INTO "KNTLword" VALUES(116,'KLOTOK','Perbedaan (selisih) kesamaan, Persamaan; ibarat, Pedoman pertimbangan');
INSERT INTO "KNTLword" VALUES(117,'KOAGEL','Gel yg terbentuk dl proses koagulasi');
INSERT INTO "KNTLword" VALUES(118,'KOMBOR','Longgar (tt celana)');
INSERT INTO "KNTLword" VALUES(119,'KOMPON','Halaman tertutup; bahan campuran');
INSERT INTO "KNTLword" VALUES(120,'KOMPOR','Perapian untuk memasak yg menggunakan minyak tanah, gas, atau listrik sbg bahan bakar;');
INSERT INTO "KNTLword" VALUES(121,'KOMPOS','Pupuk campuran yg terdiri atas bahan organik (spt daun dan jerami yg membusuk) dan kotoran hewan;');
INSERT INTO "KNTLword" VALUES(122,'KONDAI','Tanpa nama; tidak beridentitas; awanama;, Sos tidak ada penandatangannya');
INSERT INTO "KNTLword" VALUES(123,'KONDOR','Burut; hernia, Burung buas besar di pegunungan andes dng leher dan kepala tidak berbulu');
INSERT INTO "KNTLword" VALUES(124,'KONFER','Tegak lurus (tt barang panjang yg dipancangkan di tanah);, Mencacak  (men.ca.cak ), mencubit;, Mencacak  (men.ca.cak ), mencopet;');
INSERT INTO "KNTLword" VALUES(125,'KONGKO','Bercakap-cakap yg tidak ada artinya; mengobrol;');
INSERT INTO "KNTLword" VALUES(126,'KONGKR','Teluk yg dalam; cekung; cengkuk');
INSERT INTO "KNTLword" VALUES(127,'KONGSI','Persekutuan dagang; perseroan;, Perkumpulan;, Kantor tuan tanah;');
INSERT INTO "KNTLword" VALUES(128,'KONIUM','Perahu yg dijalankan dng dayung');
INSERT INTO "KNTLword" VALUES(129,'KONJEN','Tumbuhan yg bijinya dibuat obat pencuci perut atau pencahar; croton tiglium;, Biji cemekian');
INSERT INTO "KNTLword" VALUES(130,'KONKAF','Cekung');
INSERT INTO "KNTLword" VALUES(131,'KONKUR','Bahan bakar untuk pesawat terbang bukan jet');
INSERT INTO "KNTLword" VALUES(132,'KONOID','Dok kelenjar di tengah otak;, Tek benda tiga dimensi yg diperoleh apabila elips, parabola, atau hiperbola diputar mengelilingi sumbunya');
INSERT INTO "KNTLword" VALUES(133,'KONOMI','Memberi bekal');
INSERT INTO "KNTLword" VALUES(134,'KONPER','Tembaga dsb berlapis emas');
INSERT INTO "KNTLword" VALUES(135,'KONSEP','Rancangan atau buram surat dsb;, Ide atau pengertian yg diabstrakkan dr peristiwa konkret, Ling gambaran mental dari objek, proses, atau apa pun yg ada di luar bahasa, yg digunakan oleh akal budi untuk memahami hal-hal lain');
INSERT INTO "KNTLword" VALUES(136,'KONSER','Pertunjukan musik di depan umum;, Pertunjukan oleh sekelompok pemain musik yg terjadi dr beberapa komposisi perseorangan');
INSERT INTO "KNTLword" VALUES(137,'KONSOL','Balok yg satu ujungnya terpasang pd suatu penopang tetap dan ujung lainnya bebas');
INSERT INTO "KNTLword" VALUES(138,'KONSUL','Orang yg diangkat dan ditugasi sbg wakil pemerintah suatu negara dl mengurus kepentingan perdagangan atau perihal warganegaranya di negara lain;');
INSERT INTO "KNTLword" VALUES(139,'KONSUM','Penyakit menular pd ternak yg disebabkan oleh kuman bacillus anthracis, dapat juga menyerang manusia, dng menimbulkan bisul bernanah');
INSERT INTO "KNTLword" VALUES(140,'KONTAK','Hubungan satu dng yg lain, N cak sambungan arus listrik, V cak bertemu (dng); tembak-menembak');
INSERT INTO "KNTLword" VALUES(141,'KONTAL','Pundi-pundi yg digantungkan pd ikat pinggang;');
INSERT INTO "KNTLword" VALUES(142,'KONTAN','Tunai (tt pembayaran), Cak pd ketika itu juga; langsung sekaligus');
INSERT INTO "KNTLword" VALUES(143,'KONTEN','Sahabat; kawan; sanak saudara');
INSERT INTO "KNTLword" VALUES(144,'KONTER','Melawan; menentang');
INSERT INTO "KNTLword" VALUES(145,'KONTES','Perlombaan (kecantikan dsb)');
INSERT INTO "KNTLword" VALUES(146,'KONTET','Tidak dapat tumbuh menjadi besar; kerdil (tt pertumbuhan)');
INSERT INTO "KNTLword" VALUES(148,'KONTRA','Dl keadaan tidak setuju; dl keadaan menentang;, V menentang (pendapat dsb);, Berlawanan; bertentangan; kebalikan dr; lawan dr');
INSERT INTO "KNTLword" VALUES(149,'KONTUR','Garis bentuk;, Ling pola ciri-ciri yg terjadi dr pola nada, gerak nada dng atau tanpa tekanan yg meliputi sebagian atau seluruh ujaran tertentu;');
INSERT INTO "KNTLword" VALUES(150,'KONVOI','Iring-iringan mobil (kapal) dng pengawalan bersenjata;, Iring-iringan kendaraan (dl suatu perjalanan bersama), Rombongan kendaraan, pejalan kaki pergi bersama-sama sebagai satu kelompok secara sukarela atau tidak karena faktor kontrol sinyal, geometrik atau lainnya.(teks book)');
INSERT INTO "KNTLword" VALUES(151,'KONYAK','Brendi prancis berkualitas terbaik');
INSERT INTO "KNTLword" VALUES(152,'KONYAL','Markisa');
INSERT INTO "KNTLword" VALUES(154,'KONYOL','Tidak sopan; kurang ajar;, Agak gila; kurang akal;, Tidak berguna; sia-sia;');
INSERT INTO "KNTLword" VALUES(155,'KOPBAL','Sundulan thd bola (dl sepak bola); perbuatan mengekop bola');
INSERT INTO "KNTLword" VALUES(156,'KOPRAL','Pangkat golongan tamtama dl ketentaraan, satu tingkat di bawah bintara dan satu tingkat di atas prajurit, yg mencakupi kopral kepala, kopral satu, dan kopral dua;');
INSERT INTO "KNTLword" VALUES(157,'KOPROK','Permainan dadu kocok');
INSERT INTO "KNTLword" VALUES(158,'KOPROL','Gerakan berguling ke depan');
INSERT INTO "KNTLword" VALUES(159,'KOPYOK','Mengopyok (me.ngop.yok), mengocok; mengaduk; mengacau');
INSERT INTO "KNTLword" VALUES(160,'KOPYOR','Lunak dan hancur (tt bagian daging kelapa);, N kelapa yg dagingnya lunak dan hancur, A rusak krn bagian-bagiannya bercampur (tt telur);, A ki bingung');
INSERT INTO "KNTLword" VALUES(161,'KORDON','Garis pelindung; garis pertahanan');
INSERT INTO "KNTLword" VALUES(162,'KORION','Dok selaput terluar pembungkus janin;,  zool selaput luar embrio yg berfungsi sbg selaput pelindung dan pencari makanan');
INSERT INTO "KNTLword" VALUES(163,'KORNEL','Kolonel');
INSERT INTO "KNTLword" VALUES(164,'KORPUL','Acuan atau cetakan untuk memasak bikang');
INSERT INTO "KNTLword" VALUES(165,'KORSEL','Kuda-kudaan yg dapat bergerak mengikuti gerakan roda besar yg berputar pd sumbunya (komidi putar)');
INSERT INTO "KNTLword" VALUES(166,'KORWIL','Merapatkan (sandar-menyandar dsb)');
INSERT INTO "KNTLword" VALUES(167,'KOSMOS','Jagat raya; alam semesta');
INSERT INTO "KNTLword" VALUES(168,'KOSTUM','Pakaian khusus (dapat pula merupakan pakaian seragam) bagi perseorangan, regu olahraga, rombongan, kesatuan, dsb dl upacara, pertunjukan, dsb');
INSERT INTO "KNTLword" VALUES(169,'KRATON','Proses, cara, perbuatan mendebitkan');
INSERT INTO "KNTLword" VALUES(170,'KRESOL','Zat antiseptik turunan fenol yg diperoleh dr dl ter batubara');
INSERT INTO "KNTLword" VALUES(171,'KTATOR','Ranjau, Formulir');
INSERT INTO "KNTLword" VALUES(172,'KUATOR','Membantun (mem.ban.tun), menarik supaya lepas; mencabut, Sebantun (se.ban.tun), pohon kecil, toxotrophis ilicifolia');
INSERT INTO "KNTLword" VALUES(173,'KUNTAU','Pencak cara cina');
INSERT INTO "KNTLword" VALUES(174,'KUNTIT','Menguntit (me.ngun.tit), mengikut (dr belakang), Menguntit (me.ngun.tit), mengikuti (pendapat, dsb) mengekor');
INSERT INTO "KNTLword" VALUES(175,'KUNTUL','Tidak berekor; togel (tt ayam dsb), Burung bangau berbulu putih, pemangsa ikan, katak, dsb nya');
INSERT INTO "KNTLword" VALUES(176,'KUNTUM','Kuncup bunga yg hampir mekar (berkembang, Penggolong bilangan untuk bunga, Ki gadis muda;');
INSERT INTO "KNTLword" VALUES(177,'KUSTOS','Kenaikan kerentanan suatu organisme thd injeksi protein susulan (kedua)');
INSERT INTO "KNTLword" VALUES(178,'LENTOK','Terkulai ke sisi (spt sumbu pelita, spt kepala orang yg pingsan)');
INSERT INTO "KNTLword" VALUES(179,'LONCOS','Semakin ke ujung semakin runcing (spt kerucut); lancip, Gundul; licin; telanjang');
INSERT INTO "KNTLword" VALUES(180,'LONDON','Hilang dayanya; tidak manjur (tt guna-guna dsb), Tawar (tt hati, keberanian);, Kurang ingat; lalai; lengah;, Kurang (tidak) hemat; boros');
INSERT INTO "KNTLword" VALUES(181,'LONGOK','Melongok (me.lo.ngok), melihat dng mengeluarkan kepala (melalui jendela dsb), Melongok (me.lo.ngok), jk menjenguk orang sakit dsb;, Melongok (me.lo.ngok), jk menoleh');
INSERT INTO "KNTLword" VALUES(182,'LONJOR','Batang (kata penggolong bagi barang yg panjang)');
INSERT INTO "KNTLword" VALUES(183,'LONTAI','Melontai (me.lon.tai), berkeluk (tt garis dsb); melentuk');
INSERT INTO "KNTLword" VALUES(184,'LONTAK','Sebuah negeri di asia; tiongkok;, Bangsa yg tinggal di tiongkok; tionghoa;');
INSERT INTO "KNTLword" VALUES(185,'LONTAR','Melontar (me.lon.tar), melempar;, Pohon palem yg daunnya dapat ditulisi; siwalan; borassus flabellifer;, Daun pohon lontar yg digunakan orang untuk menulis cerita dsb;, Naskah kuno yg tertulis pd daun lontar');
INSERT INTO "KNTLword" VALUES(186,'LONTOK','Pendek dan besar (gemuk), Tua sekali; tua renta');
INSERT INTO "KNTLword" VALUES(187,'LONTOS','Mengangkat atau mengacungkan (tinju, tangan, dsb), Mengancam dng senjata yg diulurkan ke depan; menodongkan, Menganjurkan, Mencari keterangan (petunjuk dsb) kpd');
INSERT INTO "KNTLword" VALUES(188,'LONYOK','Lodoh kena api atau siraman air panas');
INSERT INTO "KNTLword" VALUES(189,'MANTEL','Baju panjang (biasanya dr bahan kain tebal), berlengan atau tidak berlengan untuk menyelubungi tubuh;, Zool lipatan kulit yg menyelubungi badan pd moluska, cangkang pd individu bercangkang, dan dinding tubuh pd cumi-cumi;, Geo bagian terbesar dr lapisan kulit bumi yg terdapat di bawah kerak bumi;, Geo lapisan batuan lepas pd permukaan bumi yg merupakan bahan dasar bagi pembentukan tanah;');
INSERT INTO "KNTLword" VALUES(190,'MANTOL','Mantol --> mantel');
INSERT INTO "KNTLword" VALUES(191,'MANTUL','Bagian tumbuhan yg runcing dan tajam, Bulu binatang yg kaku dan tajam, Tulang ikan yg runcing-runcing dan tajam, Ki sesuatu yg menyusahkan (memalukan, dsb)');
INSERT INTO "KNTLword" VALUES(192,'MENTAL','Terpelanting; terpental;, Terlempar kembali; berbalik arah, Ada gunanya, ada pengaruhnya (tt obat, nasihat, dsb), A bersangkutan dng batin dan watak manusia, yg bukan bersifat badan atau tenaga, N batin dan watak;');
INSERT INTO "KNTLword" VALUES(193,'MENTOK','Terantuk (pd); tidak dapat terus (tt jalan dsb); buntu');
INSERT INTO "KNTLword" VALUES(194,'MENTOL','Terna tahunan, suku lamiaceae yg membentuk stolon, bagian tanaman seluruhnya mengandung minyak asiri yg berbau harum dan dapat diekstrak dng penyulingan, setelah didinginkan menghasilkan mentol; mentha arvensis, Alkohol, c10h20o, yg diperoleh dr pelbagai kristal, digunakan sbg bahan pengharum dan penyedap pd kembang gula, minuman keras, pasta gigi, dan obat-obatan');
INSERT INTO "KNTLword" VALUES(195,'MENTOR','Pembimbing atau pengasuh (biasanya untuk mahasiswa)');
INSERT INTO "KNTLword" VALUES(196,'MENTUL','Perhiasan yg dipasang pd rambut atau sanggul, berupa tusuk sanggul bertangkai panjang dng hiasan kuntum bunga bermata (intan, berlian, atau permata imitasi) pd bagian atasnya dan dapat bergerak berayun-ayun (berangguk-angguk)');
INSERT INTO "KNTLword" VALUES(197,'MONCOR','Mengalir ke luar; memancur;, Sakit buang-buang air (sakit berak-berak)');
INSERT INTO "KNTLword" VALUES(198,'MONDOK','Pendek gemuk (tt bentuk sesuatu)');
INSERT INTO "KNTLword" VALUES(199,'MONGOL','Tidak lurus benar; tidak tepat benar; serong (tt segi empat dsb);, Agak miring (mendaki); landai');
INSERT INTO "KNTLword" VALUES(200,'MONIAL','Melakukan begitu; membuat (mengerjakan) seperti itu;');
INSERT INTO "KNTLword" VALUES(201,'MONROE','Kemunduran atau kemerosotan generasi (tidak sebaik generasi sebelumnya), Dok kemunduran, perubahan menjadi sesuatu yg rusak');
INSERT INTO "KNTLword" VALUES(202,'MONTIR','Orang yg pekerjaannya memasang, memperbaiki, dsb mesin kendaraan bermotor, dsb yg rusak');
INSERT INTO "KNTLword" VALUES(203,'MONTIT','Lokomotif kereta api perkebunan');
INSERT INTO "KNTLword" VALUES(204,'MONTOK','Gemuk berisi; gemuk padat; sintal, Besar dan berisi (tt buah dada)');
INSERT INTO "KNTLword" VALUES(205,'MONYOS','Mendapat malu (krn kalah dsb);, Malu; kemalu-maluan');
INSERT INTO "KNTLword" VALUES(206,'MUNTUL','Tumpul; majal (tidak tajam)');
INSERT INTO "KNTLword" VALUES(207,'NAFTOL','Kim zat kristal antiseptik c10h7oh dr ter batu bara, terdapat dl dua bentuk, alfa dan beta');
INSERT INTO "KNTLword" VALUES(208,'NONGOL','Muncul, datang');
INSERT INTO "KNTLword" VALUES(209,'NONTAX','Kue dr beras ketan, kelapa, dan gula');
INSERT INTO "KNTLword" VALUES(210,'NONTES','Menaruh sbg alas (tikar, daun, dsb), Mendasarkan (pendapat, tuduhan, dsb) pd');
INSERT INTO "KNTLword" VALUES(211,'NONTON','Buta mata sebelah');
INSERT INTO "KNTLword" VALUES(212,'PANTUL','Memantul (me.man.tul), menganjal (spt bola dilemparkan ke dinding); mengambul; melenting;, Memantul (me.man.tul), bergerak balik krn membentur sesuatu atau krn refleksi, dsb');
INSERT INTO "KNTLword" VALUES(213,'PENTAL','Terpental (ter.pen.tal), terpelanting jauh');
INSERT INTO "KNTLword" VALUES(214,'PENTOL','Sesuatu (bentuk) yg menonjol (agak besar); cembul; tombol; kenop;');
INSERT INTO "KNTLword" VALUES(215,'PESTOL','Pistol');
INSERT INTO "KNTLword" VALUES(216,'PINTAL','Berpintal (ber.pin.tal), berpilin (tt tali, dawai, dsb)');
INSERT INTO "KNTLword" VALUES(217,'PINTIL','Untingan benang');
INSERT INTO "KNTLword" VALUES(218,'PISTOL','Senjata api genggam yg pendek dan kecil;');
INSERT INTO "KNTLword" VALUES(219,'PODSOL','Kaki dan kuku yg panjang (pd ayam, itik, burung);, Kuku yg panjang dan tajam (pd harimau, kucing, dsb);, Gores (parut) bekas kena kuku atau digaruk;, Penggaruk; kukur;, Barang bekas spt pakaian, sepatu, dan karung');
INSERT INTO "KNTLword" VALUES(220,'POKROL','Pembela atau wakil orang yg beperkara (dl pengadilan); pengacara; advokat;, Cak orang yg pandai berbantah (berdebat, berputar lidah, dsb);');
INSERT INTO "KNTLword" VALUES(221,'PONDOH','Nama salak yg daging buahnya empuk, spt embut, rasanya tidak sepet dan tidak masam');
INSERT INTO "KNTLword" VALUES(222,'PONDOK','Bangunan untuk tempat sementara (spt yg didirikan di ladang, di hutan, dsb); teratak, Rumah (sebutan untuk merendahkan diri), Bangunan tempat tinggal yg berpetak-petak yg berdinding bilik dan beratap rumbia (untuk tempat tinggal beberapa keluarga);, Madrasah dan asrama (tempat mengaji, belajar agama islam); ');
INSERT INTO "KNTLword" VALUES(223,'PONSEL','Gerakan, N tindakan, N sikap (gerak-gerak, tingkah laku) yg dibuat-buat, A cak elok sekali (tt pakaian, tingkah laku, dsb)');
INSERT INTO "KNTLword" VALUES(224,'PONTEN','Angka (biji, nilai) kepandaian atau angka pertandingan (perlombaan);');
INSERT INTO "KNTLword" VALUES(225,'PONTOH','Gelang besar dr emas atau perak yg berukir naga atau merak yg dipakai di lengan atas (di atas siku) atau di atas pergelangan tangan');
INSERT INTO "KNTLword" VALUES(226,'PONTON','Sampan yg rendah dan lebar untuk menggalang atau menyangga jembatan darurat dsb');
INSERT INTO "KNTLword" VALUES(227,'PORTAL','Pintu gerbang; gapura;, Jalan (pintu) masuk ke dl tambang bawah tanah, terowongan, jembatan, dsb;, Gang (beranda dsb) lebar di depan kamar-kamar dl rumah, gedung, dsb;, Cak tonggak atau palang yg dipasang di ujung gang (jalan) untuk menghalangi masuknya kendaraan tertentu');
INSERT INTO "KNTLword" VALUES(228,'POSTEL','Masa bodoh; tidak acuh');
INSERT INTO "KNTLword" VALUES(229,'PUNTAL','Berpuntal-puntal (ber.pun.tal-pun.tal), bergulung-gulung spt dipintal atau disiplin, Berpuntal-puntal (ber.pun.tal-pun.tal), beberapa kumpulan (gulung) benang, tali, dsb');
INSERT INTO "KNTLword" VALUES(230,'PUNTUL','Tumpul');
INSERT INTO "KNTLword" VALUES(231,'RENTAL','Persewaan');
INSERT INTO "KNTLword" VALUES(232,'RONDOK','Berondok (be.ron.dok), bersembunyi dng berjongkok di balik semak dsb');
INSERT INTO "KNTLword" VALUES(233,'RONGOS','Merongos (me.ro.ngos), mudah (lekas) marah');
INSERT INTO "KNTLword" VALUES(234,'RONGOT','Rongot --> rungut');
INSERT INTO "KNTLword" VALUES(235,'RONTAL','Makhluk, plankton, zarah hidup spt spora, bakteri, dan serbuk sari yg melayang di udara dan dipencarkan oleh angin');
INSERT INTO "KNTLword" VALUES(236,'RONTEK','Bendera kecil yg dihiaskan pd tombak');
INSERT INTO "KNTLword" VALUES(237,'RONTOK','Jatuh atau gugur dl jumlah yg banyak (tt buah-buahan, daun-daunan), Luruh (tt bulu, rambut, dsb), Lepas; mengelupas (tt cat, bedak), Banyak tanggal (tt gigi), Ki kalah');
INSERT INTO "KNTLword" VALUES(238,'RONYOK','Renyuk; kumal; berkerut-kerut;');
INSERT INTO "KNTLword" VALUES(239,'SENTAL','Menyental (me.nyen.tal), menggosok kuat-kuat (supaya bersih dsb)');
INSERT INTO "KNTLword" VALUES(240,'SENTIL','Tampak tersembul sedikit di antara bibir (sugi, gula-gula, dsb); tersongel, Menyentil (me.nyen.til), menjentik; menggetik, Menyentil (me.nyen.til), menyinggung; menyentuh;, Menyentil (me.nyen.til), ki menegur (dl arti memarahi); mengkritik');
INSERT INTO "KNTLword" VALUES(241,'SENTOL','Pendek atau gemuk');
INSERT INTO "KNTLword" VALUES(242,'SENTUL','Pohon, buahnya dapat dimakan, masam rasanya, kayunya dibuat papan; kecapi; sandoricum koetjape;, Buah sentul;, Kayu sentul');
INSERT INTO "KNTLword" VALUES(243,'SINEOL','Enkaliptol');
INSERT INTO "KNTLword" VALUES(244,'SINTAL','Gemuk padat atau padat berisi (tt tubuh), Kenyal atau tebal dan kencang (tt daging)');
INSERT INTO "KNTLword" VALUES(245,'SINTIL','Kain mori yg masih mentah (belum diputihkan) sehingga warnanya agak kekuning-kuningan');
INSERT INTO "KNTLword" VALUES(246,'SISTOL','Makan; santap');
INSERT INTO "KNTLword" VALUES(247,'SOFBOL','Proses, cara, perbuatan mencoret');
INSERT INTO "KNTLword" VALUES(248,'SOMBOL','Menyombol (me.nyom.bol), menyuapi (makanan dsb) dng paksa');
INSERT INTO "KNTLword" VALUES(249,'SONDOK','Gombak di dahi; jambak (jambul) pd dahi kuda');
INSERT INTO "KNTLword" VALUES(250,'SONDOL','Sondol --> sundul');
INSERT INTO "KNTLword" VALUES(251,'SONGEL','Tersongel');
INSERT INTO "KNTLword" VALUES(252,'SONTAK','Sompek; sumbing, Mendadak sontak, (dng) sekonyong-konyong; (dng) tiba-tiba');
INSERT INTO "KNTLword" VALUES(253,'SONTEK','Menyontek, Menyontek');
INSERT INTO "KNTLword" VALUES(254,'SONTOK','Pendek; singkat, Menyontok (me.nyon.tok), menumbuk; menggocoh');
INSERT INTO "KNTLword" VALUES(255,'SOSIOL','Sudah ada cenanya; sudah terbukti');
INSERT INTO "KNTLword" VALUES(256,'SOSPOL','Orang (panitia, organisasi, dsb) yg menentukan banyaknya catu; pemberi catu;');
INSERT INTO "KNTLword" VALUES(257,'SUNTIL','Melakukan analisis;');
INSERT INTO "KNTLword" VALUES(258,'TOKTOK','Batang kayu yg berongga (terdapat di surau dsb) yg dipukul untuk memanggil orang agar salat, berkumpul, dsb');
INSERT INTO "KNTLword" VALUES(259,'TOMBOL','Alat (knop) pd mesin dsb, yg gerak tekan atau gerak tariknya dapat menjalankan, menghentikan, atau mengubah gerak pd mesin;, Tonjolan pd kulit (orang, binatang, kayu, dsb)');
INSERT INTO "KNTLword" VALUES(260,'TONGOL','Menongol (me.no.ngol), menyembulkan kepala; muncul (menampakkan diri)');
INSERT INTO "KNTLword" VALUES(261,'TONJOK','Tinju;');
INSERT INTO "KNTLword" VALUES(262,'TONJOL','Jendul (di kulit, di dahi, dsb); sesuatu yg tampak berjendul;');
INSERT INTO "KNTLword" VALUES(263,'TONSIL','Amandel');
INSERT INTO "KNTLword" VALUES(264,'TONTON','Menonton (me.non.ton), melihat (pertunjukan, gambar hidup, dsb)');
INSERT INTO "KNTLword" VALUES(266,'WORTEL','Tanaman sayuran berakar pasak berdaging, berwarna kuning jingga, kaya akan zat gula, vitamin, dan garam mineral; daucus carota');
COMMIT;
